name: Spark CI

on:
  push:
    tags:
      - "v*"
    branches: [main]
  workflow_call:
jobs:
  ash-ci:
    uses: ash-project/ash/.github/workflows/ash-ci.yml@main
    with:
      spark-formatter: false
