name: Spark CI

on:
  push:
    branches: [main]
    tags-ignore: ["v*"]
  pull_request:
    branches: [main]
  create:
    tags: ["v*"]
    branches: main
jobs:
  ash-ci:
    uses: ash-project/ash/.github/workflows/ash-ci.yml@main
